//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppointmentDiary
    {
        public int ID { get; set; }
        public string IdProfessore { get; set; }
        public string idUtente { get; set; }
        public System.DateTime DateTimeScheduled { get; set; }
        public string Title { get; set; }
        public string nomeProfessore { get; set; }
        public Nullable<int> AppointmentLength { get; set; }
        public Nullable<int> StatusENUM { get; set; }
        public string Message { get; set; }
    }
}
